### ISSUE TITLE
Unable to cirvument captcha

### ISSUE THREAD

**Issue by gsotiriou** [walthowd/ha-alexa-tts#11]
I am getting a captcha screen at .alexa.login and there is no success circumventing it.
I have tried the following:

1. Using firefox with disabled javascript and cleaned up cookies to login to alexa.amazon.com
2. Using chrome with disabled javascript and cleaned up cookies to login to alexa.amazon.com
3. Using chrome extension you suggested to get "all cookies" into cookies.txt and:
- Copy/Pasted cookies.txt into the SAMBA share folder homeassistant on Windows
- Renamed cookies.txt to -> .alexa.cookie (at which point disappeared from file explorer).
- Logged in via SSH on Pi navigated to /home/homeassistant/.homeassistant
- Executed: sudo mv .alexa.cookie /tmp
- Navigated to /tmp
- Executed chown and chgrp to set owner and group of .alexa.cookie to 'pi' (same as .alexa.login)
- Navigated back to /home/homeassistant/.homeassistant
- Executed the script ./alexa_remote_control.sh -a as per instructions.
- Nevative result , got captcha again.

Is it still working or has Amazon blocked it? Am I doing anything wrong based on the above?

**Comment by walthowd** [comment]
Your line endings might be wrong if created the cookies.txt file on Windows. You also don't need to disable javascript if you are using the cookies.txt extension. The easiest way to transfe over the cookies might to be just login via SSH as your Home Assistant user and paste it in.

```
vi /tmp/.alexa.cookie
:set paste
i
CTRL+V
:wq
```

**Comment by gsotiriou** [comment]
I permanently get the message:
"cookie expired, logging in again ..."
and after a short wait I get the captcha message again.

I don't mean to harangue in any way but are we sure this is still working and Amazon hasn't found a way to block it?

**Comment by angel12** [comment]
Are you using hass.io by chance? I am using hass.io on a VM, and while I can get it to authenticate correctly on the VM, in the hass.io home-assistant docker I consistently get that error as well.

**Comment by gsotiriou** [comment]
@angel12 no I am using the hassbian based installation.

**Comment by walthowd** [comment]
It is still working for other people, though the automatic logon does not seem to work for anyone in the United States -- However the cookie work around should work if properly formatted.

**Comment by gsotiriou** [comment]
My vi seems to have some kind of bug when I am pasting - I googled the specific error didn't get much sense out of it , but as it turns out the only option I have is transfer the file via windows , move it , rename it and use it like that. 

If you think that this is destroying the formatting (line endings) is there some way I could manually edit the file to fix it ?

**Comment by walthowd** [comment]
Yes, just download the sublime text editor. Paste the cookies into a new file in sublime and select UNIX line endings from the view menu. Then transfer that file via your normal method and you should be fine.

**Comment by gsotiriou** [comment]
@walthowd should the file be looking like a JSON?

**Comment by walthowd** [comment]
No, it should look like this:

```
# HTTP Cookie File for github.com by Genuinous @genuinous.
# To download cookies for this tab click here, or download all cookies.
# Usage Examples:
#   1) wget -x --load-cookies cookies.txt "https://github.com/walthowd/ha-alexa-tts/issues/11#issuecomment-405049008"
#   2) curl --cookie cookies.txt "https://github.com/walthowd/ha-alexa-tts/issues/11#issuecomment-405049008"
#   3) aria2c --load-cookies cookies.txt "https://github.com/walthowd/ha-alexa-tts/issues/11#issuecomment-405049008"
#
.github.com	TRUE	/	FALSE	1551041082	_octo	GH1.1.1934983367.1487969082
.github.com	TRUE	/	TRUE	2144424807	logged_in	yes
.github.com	TRUE	/	TRUE	2144424807	dotcom_user	walthowd
.github.com	TRUE	/	FALSE	1594820131	_ga	GA1.2.157129354.1423242299
github.com	FALSE	/	TRUE	1532957732	user_session	CE4fnFaHnnf-5Nworkitworkitm-1eqHX
github.com	FALSE	/	TRUE	1532957732	__Host-user_session_same_site	CD4fnBaHnMf-kjhasdiuasdknjasd-1eqHX
github.com	FALSE	/	TRUE	0	tz	America%2FChicago
gist.github.com	FALSE	/	TRUE	0	tz	America%2FChicago
```
