### ISSUE TITLE
TTS is ignoring ? and ! chars

### ISSUE THREAD

**Issue by Ezeta31** [walthowd/ha-alexa-tts#13]
When sending TTS command like:

`alexa_remote_control.sh -d 'Echo Salon' -e speak:"hey? Is there someone?"`

The TTS seems well passed to the script, but Alexa is ignoring ? character, like if they were removed from the string (she is prononing the sentence without pause and without question intonation).
The same problem occurs with ! character, while it is correctly working with dot and coma (. or ,).

**Comment by maxvet** [comment]
Try adding underscore instead of space in your sentence.

**Comment by Ezeta31** [comment]
I tried, but it does not change anything.

**Comment by Ezeta31** [comment]
After some more tests, it seems that the problem is at the level of Amazon: when creating, through Alexa app, a routine making speaking Alexa, the same problem occurs: ! And ? Are not taken into account in the spoken sentence.
