### ISSUE TITLE
Add feature announcment

### ISSUE THREAD

**Issue by Gibby** [walthowd/ha-alexa-tts#14]
Can a SEQUENCECMDs be added for announcements?

**Comment by walthowd** [comment]
Should be fairly easy to add but I haven't found the API/back end commands documented anywhere? I don't see them on the loetzmer.de script or the OpenHAB echo control bindings. Have you seen them anywhere?

**Comment by Gibby** [comment]
No I don't, but continued reading your README and figured out -d 'ALL' does almost the same thing.

I

**Comment by walthowd** [comment]
That's true, though you don't get the cool dinner bell for "dinner's ready!" and all the other context sensitive prefixes. :)
