### ISSUE TITLE
Amazon cookie issue

### ISSUE THREAD

**Issue by brahmafear** [walthowd/ha-alexa-tts#2]
Receiving error on first login (as expected).  Followed procedure for logging in via chrome and using cookie.txt extension to save cookie.  Moved cookie in to correct location.

Upon subsequent runs of `alexa_remote_control.sh -a` receive message that cookie is expired, logging in again.  Login again fails.  

Any other workarounds for this?

**Comment by juan11perez** [comment]
this worked for me.
clear cookies from your browser. pull a new cookie.
copy (dont move it) it to the correct location. Once in place do sudo chmod 777 /tmp/.alexa.cookie
delete the exiting .alexa.login

the run the remote command.

**Comment by brahmafear** [comment]
Working now.  Had to use Firefox with similar cookies.txt extension.
